all:	q1	q2	q3	q4	q5	q6

q1:
	gcc -o fifop1 fifop1.c

q2:
	gcc -o fifop2 fifop2.c

q3:
	gcc -o socketp1 socketp1.c

q4:
	gcc -o socketp2 socketp2.c

q5:
	gcc -o sha1 sharedmemp1.c

q6:
	gcc -o sha2 sharedmemp2.c

